### ISSUE TITLE
Sourcecode and license for the MediaTek jar files?

### ISSUE THREAD

**Issue by krt16s** [jbardera/RoamingInfo#3]

**Comment by jbardera** [comment]
http://labs.mediatek.com/site/global/developer_tools/mediatek_android/mediatek_sdk_android/index.gsp

License

Single User license Only - Subject to your compliance with these terms and conditions, MediaTek grants you a personal, freely revocable, limited, royalty-free, non-exclusive, non-transferable, non-sublicensable, non-assignable license to use the Tools Software, solely for your personal, internal developing and testing application related purposes

**Comment by krt16s** [comment]
Too bad, that makes the software non-free :/

**Comment by jbardera** [comment]
No. The license above refers only to Mediatek Tools Software (this is the one non-free), which includes an emulator to test your app and a DDMS to manage it, etc.
The software (source code) that you produce is not subjected to this license. In this case I offer it free.

**Comment by krt16s** [comment]
The jar you use are proprietary non-free software. While your main projects is still public domain, the jars aren't. Thus fdroid, a free/libre/opensource app-store can no longer build the project.

Or is there an easy way to strip those jars, providing a "pure-floss" build (with reduced functionality)?

**Comment by jbardera** [comment]
The jars are pure interfaces, they are only calls to the real functions coded in their Android version. From a legal point of view by using Android anyone is tied to its original license which forbids making proprietary versions of Android. There is some dispute with Mediatek, amongst other brands that modify Android for their devices, because they don't reveal the source code, or delay doing it. This has being covered by the press, see for example at http://www.gizchina.com/2014/03/24/mediatek-dont-share-source-code/ 
There is a petition at change.org to ask Mediatek comply with the GPL license, see https://www.change.org/p/mediatek-inc-release-kernel-sources-for-android-socs-and-comply-with-the-gpl
But until now you're right, we can not say it is free because they have not yet released the code.
You can easily modify my source code to avoid the use of Mediatek API: at RoamingInfoService.java just change the lines:
toShow="[1] ";
try { mgMtk= new TelephonyManagerEx(this); } catch (Exception e) { weMtk=false; toShow=""; } //!weMtk in case no Mediatek
by
toShow="";
weMtk=false;
And delete all the if (weMtk) { .. } enclosure.
This way it will work showing only one notification (for the first SIM on Mtk Socs).

**Comment by krt16s** [comment]
Thanks for the hints, builds fine.
